<?php
/**
 * ZF2rapid library
 *
 * @package    ZFrapidLibrary
 * @link       https://github.com/ZFrapid/zfrapid-library
 * @copyright  Copyright (c) 2014 - 2016 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Bootstrap alert widget view script
 *
 * @package    ZFrapidLibrary
 */
?>
<div class="alert alert-dismissible <?php echo $this->alertClass; ?>">
    <button class="close" data-dismiss="alert" type="button">×</button>
    <h3><?php echo $this->translate($this->alertMessage); ?></h3>
</div>