<?php
/**
 * ZF2rapid library
 *
 * @package    ZFrapidLibrary
 * @link       https://github.com/ZFrapid/zfrapid-library
 * @copyright  Copyright (c) 2014 - 2016 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Bootstrap form group widget view script
 *
 * @package    ZFrapidLibrary
 */
?>
<?php if ($this->element->getOption('heading')) : ?>
    <h4>
        <?php echo $this->translate($this->element->getOption('heading')) ?>
    </h4>
<?php endif; ?>
<div class="form-group">
    <?php echo $this->formLabel($this->element); ?>
    <div class="col-sm-10">
        <?php echo $this->formElement($this->element); ?>
        <?php echo $this->formElementErrors($this->element); ?>
        <?php if ($this->element->getOption('help_block')) : ?>
            <span class="fa fa-info-circle"></span>&nbsp;
            <?php
            echo $this->translate(
                $this->element->getOption('help_block')
            );
            ?>
            </span>
        <?php endif; ?>
    </div>
</div>