<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'zfrapid-library/widget/bootstrap-alert'       => __DIR__ . '/../view/zfrapid-library/widget/bootstrap-alert.phtml',
    'zfrapid-library/widget/bootstrap-form-submit' => __DIR__ . '/../view/zfrapid-library/widget/bootstrap-form-submit.phtml',
    'zfrapid-library/widget/bootstrap-form-group'  => __DIR__ . '/../view/zfrapid-library/widget/bootstrap-form-group.phtml',
);
